#!/usr/bin/env bash
# test/e2e/refresh-screenshots.sh — refresh the README feature tour.
#
# The tours in this directory already produce every screenshot the project needs;
# their output lives in catalog/ which is a BUILD ARTIFACT (gitignored, rebuilt by
# CI on every run). This script promotes that output to the committed set the
# top-level README links to:
#
#   1. runs both tours   (run.sh — feature walkthrough + beta funnel)
#   2. optimizes the PNGs into docs/screenshots/   (~50% smaller, same resolution)
#   3. rewrites the README tour section from the tours' own manifest.json captions
#
# Step 3 is why the captions in the README are never hand-copied: they are
# generated between the <!-- BEGIN/END FEATURE-TOUR --> markers, so a caption
# edited in run-tour.mjs / beta-tour.mjs reaches the README by re-running this.
#
#   bash test/e2e/refresh-screenshots.sh            # full: run tours, then promote
#   SKIP_TOURS=1 bash test/e2e/refresh-screenshots.sh   # promote an existing catalog/
#
# Screenshots are nicest with a local ollama running (run.sh points at it
# automatically); without one the server's deterministic fallback still produces a
# complete, if less interesting, tour.
set -euo pipefail
cd "$(dirname "$0")"                                  # refimpl/racketmaximus/test/e2e
E2E="$(pwd)"
ROOT="$(cd ../../../.. && pwd)"                       # repo root
DEST="$ROOT/docs/screenshots"

if [ "${SKIP_TOURS:-0}" != "1" ]; then
  echo "== running the tours =========================================="
  bash run.sh
fi

[ -f "$E2E/catalog/manifest.json" ] || { echo "no catalog/ — run without SKIP_TOURS=1" >&2; exit 1; }

echo "== promoting screenshots to docs/screenshots =================="
mkdir -p "$DEST/beta"
rm -f "$DEST"/*.png "$DEST"/beta/*.png

# Quantize to a 256-colour palette: these are flat UI screenshots, so it is
# visually lossless here and roughly halves the byte count. Do NOT downscale —
# resampling *increases* PNG size (more distinct colours) and blurs the text.
have(){ command -v "$1" >/dev/null 2>&1; }
promote(){ # <src-dir> <dst-dir>
  for f in "$1"/*.png; do
    local out="$2/$(basename "$f")"
    if have convert; then convert "$f" -strip -colors 256 "$out"; else cp "$f" "$out"; fi
    if have optipng; then optipng -quiet -o2 "$out"; fi
  done
}
promote "$E2E/catalog"      "$DEST"
promote "$E2E/catalog/beta" "$DEST/beta"
have convert  || echo "  note: ImageMagick not found — copied unoptimized"
have optipng  || echo "  note: optipng not found — skipped final pass"

# the manifests travel with the images: they are the caption source of truth
cp "$E2E/catalog/manifest.json"      "$DEST/manifest.json"
cp "$E2E/catalog/beta/manifest.json" "$DEST/beta/manifest.json"

echo "== regenerating the README tour section ======================="
python3 - "$ROOT" <<'PY'
import json, sys, pathlib

root = pathlib.Path(sys.argv[1])
readme = root / "README.md"
shots = root / "docs" / "screenshots"

def section(manifest, prefix, level="###"):
    out = []
    for e in json.load(open(manifest)):
        out.append(f"{level} {e['title']}\n")
        out.append(f"![{e['title']}]({prefix}{e['file']})\n")
        out.append(f"{e['caption']}\n")
    return "\n".join(out)

body = [
    "<!-- Generated by refimpl/racketmaximus/test/e2e/refresh-screenshots.sh — do not edit by hand. -->",
    "",
    "Every screenshot below is produced by the Playwright tours in",
    "[`refimpl/racketmaximus/test/e2e/`](refimpl/racketmaximus/test/e2e/), which drive a real",
    "server on a throwaway database — nothing here is a mockup. CI runs those same tours on",
    "every push, so the flows stay exercised; the images committed here are refreshed by",
    "re-running the script noted below.",
    "",
    section(shots / "manifest.json", "docs/screenshots/"),
    "",
    "### Beta onboarding funnel",
    "",
    "A pre-sales lead funnel that a deployer skins and owns — three render tiers, all through",
    "one anti-abuse gate. See [docs/design/beta-onboarding-experience.md](docs/design/beta-onboarding-experience.md).",
    "",
    "<details>",
    "<summary><b>10 more screenshots — the public funnel, the LLM judge, and all three render tiers</b></summary>",
    "",
    section(shots / "beta" / "manifest.json", "docs/screenshots/beta/", level="####"),
    "</details>",
]

text = readme.read_text()
begin, end = "<!-- BEGIN FEATURE-TOUR -->", "<!-- END FEATURE-TOUR -->"
if begin not in text or end not in text:
    sys.exit(f"markers {begin} / {end} not found in README.md")
head, rest = text.split(begin, 1)
_, tail = rest.split(end, 1)
readme.write_text(f"{head}{begin}\n\n" + "\n".join(body).rstrip() + f"\n\n{end}{tail}")
print(f"  README.md tour section rewritten")
PY

echo
echo "done — $(ls "$DEST"/*.png "$DEST"/beta/*.png | wc -l) screenshots, $(du -sh "$DEST" | cut -f1)"
