#!/usr/bin/env bash
# Telemachus e2e: boot throwaway servers on temp DBs, drive the whole UI with
# Playwright, and build the screenshot catalogs.  Usage: bash test/e2e/run.sh
#
# Two tours, because they need different servers:
#   1. feature tour  — home routing = login (the default), console at /
#   2. beta tour     — home routing = beta, the funnel at /, on its own fresh DB
# One server cannot serve both: TELEMACHUS_HOME is a server-side setting, and the
# beta tour bootstraps its own operator, so it needs a database nobody touched.
set -e
cd "$(dirname "$0")"

# This box's default node is too old for Playwright; prefer a modern one if present.
for v in v24.18.0 v22.22.3 v20.17.0; do
  if [ -x "$HOME/.nvm/versions/node/$v/bin/node" ]; then
    export PATH="$HOME/.nvm/versions/node/$v/bin:$PATH"; break
  fi
done
echo "node $(node -v)"

[ -d node_modules/@playwright ] || npm install
npx playwright install chromium chromium-headless-shell >/dev/null 2>&1 || true

# Use a local ollama model if one is reachable (nicer, real screenshots); with
# none, the server falls back to a deterministic reply so the tours still pass.
if [ -z "${TELEMACHUS_MODEL_URL:-}" ] && curl -sf http://127.0.0.1:11434/api/tags >/dev/null 2>&1; then
  export TELEMACHUS_MODEL_URL=http://127.0.0.1:11434/v1/chat/completions
  export TELEMACHUS_MODEL="${TELEMACHUS_MODEL:-qwen2.5:7b}"
  echo "model: ollama ($TELEMACHUS_MODEL)"
else
  echo "model: deterministic fallback (no ollama reachable)"
fi

# Override PORT to run the tours alongside a dev server holding the default port.
PORT="${PORT:-8835}"
BETA_PORT="${BETA_PORT:-$((PORT + 1))}"

SRVS=(); DIRS=()
cleanup() {
  for p in "${SRVS[@]:-}"; do [ -n "$p" ] && kill "$p" 2>/dev/null || true; done
  for d in "${DIRS[@]:-}"; do [ -n "$d" ] && rm -rf "$d"; done
}
trap cleanup EXIT

# boot <port> <logfile> [VAR=value ...] — fresh temp DB, waits for /health
boot() {
  local port="$1" log="$2"; shift 2
  local dir; dir="$(mktemp -d)"; DIRS+=("$dir")
  ( export E2E_DATA_DIR="$dir" PORT="$port" ${1+"$@"}; exec bash boot-server.sh ) >"$log" 2>&1 &
  SRVS+=("$!")
  echo -n "waiting for server on $port"
  for _ in $(seq 1 120); do
    if curl -sf "http://127.0.0.1:$port/health" >/dev/null 2>&1; then echo " up"; return 0; fi
    echo -n .; sleep 0.5
  done
  echo " FAILED"; tail -25 "$log"; return 1
}

# ── 1. feature tour ──────────────────────────────────────────────────────────
boot "$PORT" /tmp/telemachus-e2e-server.log
BASE_URL="${BASE_URL:-http://127.0.0.1:$PORT}" node run-tour.mjs
node build-catalog.mjs
echo "catalog → $(pwd)/catalog/catalog.html"

# ── 2. beta onboarding tour ──────────────────────────────────────────────────
boot "$BETA_PORT" /tmp/telemachus-e2e-beta-server.log TELEMACHUS_HOME=beta
BASE_URL="http://127.0.0.1:$BETA_PORT" node beta-tour.mjs
node build-catalog.mjs beta \
  "Telemachus — Beta Onboarding" \
  "A Playwright walk through the pre-sales funnel: the public landing, anti-abuse on submit, the LLM judge and owner review, and all three render tiers — the built-in themeable shell, a console-authored HTML template, and a fully custom plugin bundle." \
  "Generated by test/e2e/beta-tour.mjs — a headless Playwright tour that boots a beta-mode server on a fresh database, drives the real funnel, and captures this catalog."
echo "catalog → $(pwd)/catalog/beta/catalog.html"
